### ISSUE TITLE
Supporting WebSockets

### ISSUE THREAD

**Issue by shimonchayim** [LearnBoost/cluster#103]
Does Cluster support WebSockets? When using with websocket-server I get into problems. If the support is already there, could you please point me to an example or some other pointer?

**Comment by tj** [comment]
cluster will support anything node supports, it's not a reverse proxy (the kernel handles load balancing)

**Comment by indexzero** [comment]
@shimonchayim I think you're looking for socket.io: http://github.com/learnboost/socket.io ... node-websocket-server is not maintained as heavily.

**Comment by shimonchayim** [comment]
Will try using socket.io
