### ISSUE TITLE
Use of Math.random() with workers

### ISSUE THREAD

**Issue by cronnelly** [LearnBoost/cluster#112]
This isn't an issue with cluster as such, but a consequence of the rapid spawning of the workers, which I'd like to bring to attention.

Basically, since the workers spawn almost at the same time, and Javascript's Math.random() function seeds based on time, there is a chance of multiple workers having the same seed. Therefore different workers will produce the same sequence of output from Math.random().

Here is a very simple test:

``` javascript
var cluster = require('cluster');
var app = require('express').createServer();

app.get('/', function(req, res){
    res.send('Hello World');
});

console.log("starting pid " + process.pid);
console.log(Math.random());

cluster(app).listen(3000);
```

And the output:

```
~/test  ᐅ node server.js
starting pid 12537
0.9381190612912178
starting pid 12541
0.587162729119882
starting pid 12539
0.05383983580395579
starting pid 12545
0.4476612084545195 <--- DUPLICATE
starting pid 12542
0.3652953701093793
starting pid 12540
0.4075929725077003
starting pid 12544
0.4476612084545195 <--- DUPLICATE
starting pid 12543
0.37923460197634995
starting pid 12546
0.06591962883248925
```

Is there anything that could be done to ensure each worker starts with a different seed?

Thanks,
Mike

**Comment by tj** [comment]
no clue, I dont think js has access to that, though you should't rely on Math.random() alone for UIDs etc

**Comment by cronnelly** [comment]
Fair enough. Thanks!
