### ISSUE TITLE
Bind to port 80 and give up privileges

### ISSUE THREAD

**Issue by zdzolton** [LearnBoost/cluster#116]
Hi,

I have a web app that gets executed as root, binds to port 80 and then changes itself to a less-priviledged user.

When I try to add Cluster into the mix I receive an "Error: EACCES, Permission denied" error, at cluster/lib/master.js:791, which looks like the line where the master process binds to the port. I am calling listen() before setuid(), which worked before, but I'm guessing there's more to the story here.

Any ideas of what I should try?

Thank you,

Zach

**Comment by tj** [comment]
there's a "user" and "group" setting you can try, those sys calls are deferred until each worker calls listenFD()

**Comment by zdzolton** [comment]
Thank you, that worked!

**Comment by tj** [comment]
woot
