### ISSUE TITLE
node 0.4.9 + express + cluster

### ISSUE THREAD

**Issue by matthiasak** [LearnBoost/cluster#118]
var express = require('express'),
    cluster = require("cluster");
var app = module.exports = express.createServer();

app.get('/timezones/:location', process_tz_search); 
app.get('/timezones/', process_tz_search); 

app.listen(9000);

throws an error: 

Error: EPERM, Operation not permitted
    at Server._doListen (net.js:1100:5)
    at net.js:1048:16

Anyone know why this happens with such simple app?

**Comment by tj** [comment]
doesn't even look like you're using cluster, it's just sitting there as a var

**Comment by matthiasak** [comment]
whoops, sorry, i had this commented out after it was failing :)

cluster(app)
    .use(cluster.reload())
    .use(cluster.stats())
    .use(cluster.repl(8888))
    .listen(9000);

**Comment by tj** [comment]
hmm looks fine to me :s try commenting out the repl line, maybe that port is blocked or something one of those is failing

**Comment by matthiasak** [comment]
Error: EPERM, Operation not permitted
    at Server._doListen (net.js:1100:5)
    at net.js:1048:16

after

cluster(app).listen(9000);

**Comment by tj** [comment]
weird, usually there's no issue with high ports like that, guess try sudo then

**Comment by matthiasak** [comment]
Unfortunately that didn't change anything either. Here are the versions of packages i am using:

/mnt/hgfs/www/nodejs
├─┬ cluster@0.6.4 -> /usr/local/lib/node_modules/cluster
│ └── log@1.2.0 
├─┬ express@2.4.0 -> /usr/local/lib/node_modules/express
│ ├── connect@1.5.1 
│ ├── mime@1.2.2 
│ └── qs@0.2.0 
└── xmlhttprequest@1.0.0 -> /usr/local/lib/node_modules/xmlhttprequest

**Comment by matthiasak** [comment]
I also just ran update, eexpress updated to 2.4.2

**Comment by tj** [comment]
can you bind to that port with node's http.Server instead of express/cluster etc? or just with express

**Comment by matthiasak** [comment]
I can, running straight up express works beautifully.

Is there an error in the object returned from express?

Thank you for the swift feedback, I owe you a beer :)

On Thu, Jul 7, 2011 at 3:18 PM, visionmedia <
reply@reply.github.com>wrote:

> can you bind to that port with node's http.Server instead of
> express/cluster etc? or just with express
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/LearnBoost/cluster/issues/118#issuecomment-1525889

## 

Matt Keas (http://mkeas.org) @matthiasak

Senior Software Developer
2nd.MD
Easy access to leading doctors
http://2nd.md

**Comment by tj** [comment]
what version of node? strange that it's an EPERM issue, maybe it's failing to create the local sockets

**Comment by matthiasak** [comment]
0.4.9

**Comment by tj** [comment]
hmm not sure, tough for me to debug without a terminal, just seems though like you dont have write permissions to that directory or something (that's where cluster will by default create the IPC sock)

**Comment by matthiasak** [comment]
It seems that was indeed the case, while it was trying to create the files, the folder was in a shared folder space under a centOS VM
