### ISSUE TITLE
New worker for each request

### ISSUE THREAD

**Issue by felixge** [LearnBoost/cluster#123]
Hi TJ,

I'm wondering if it's possible to isolate file uploads into one request per worker using cluster. Here is what I have in mind:

``` javascript
function (req, res) {
   // code to receive upload,

  // stop accepting connections with this work, tell cluster to spawn a new one
  worker.close();
}
```

So in a worker I basically need the ability to tell the master to gracefully shut the worker down, and start a new worker for it right away.

Is that currently possible?

--fg

**Comment by tj** [comment]
hmm you can just exit() and cluster will get **SIGCHLD** and spawn you a new worker, _but_ the only way I can think of to limit it to a single request is to immediately stop the sever's watcher so it wont accept more connections. Should work :D

**Comment by felixge** [comment]
> but the only way I can think of to limit it to a single request is to immediately stop the sever's watcher so it wont accept more connections. Should work :D

I can stop the watcher, but I also want to signal the master that it needs to spawn a new worker because the current one will no longer accept connections. Got any ideas for that? Would I be able to write a plugin that lets me message the master from a worker?

**Comment by tj** [comment]
oh I see, to spawn one _while_ it's still active. `Master#spawn(n)` is the method we would want to get at for that. I haven't tried but within the worker or plugin `master.call('spawn', 1)` should work

**Comment by felixge** [comment]
Awesome, thanks - I'll try. Btw. I'm working on an experimental new branch for transloadit using cluster, if it goes well it will run on 20 machines next week : ).

**Comment by tj** [comment]
nice!! that's awesome

**Comment by felixge** [comment]
Thanks for merging!

Btw. it turned out that the more elegant solution was to write a plugin:

https://github.com/felixge/node-cluster-isolatable

Btw. I'm very impressed with cluster, great work : ).

**Comment by tj** [comment]
thanks man. still a few rough edges but it's a decent start

**Comment by felixge** [comment]
> still a few rough edges but it's a decent start

Are you talking about cluster or cluster-isolatable? Both seem to work well now for me : )

**Comment by tj** [comment]
cluster :D

**Comment by tj** [comment]
I'm curious though what's the use-case for isolating a single request per worker? (instead of 5, 10, etc?)

**Comment by tommedema** [comment]
@felixge, I'm wondering, did you build an extension to cluster that allows you to manage multiple servers each running multiple processes? I'm in need of the same functionality, but would hate to reinvent the wheel.

**Comment by tj** [comment]
@tommedema I'd be interested in that too, it's not something I need right now but obviously will in the future. I think it should be generally pretty simple, though it might need an abstraction layer for cluster communication as far as communicating with multiple clusters via the REPL etc, _but_ then again there are times you would want to drill down to a cluster running on a single machin via the REPL as well so centralized stuff could be separate I suppose.

There are some related plugins available already such as the redis log plugin, might be nice to integrate redis for a management plugin as well

**Comment by felixge** [comment]
> I'm curious though what's the use-case for isolating a single request per worker? (instead of 5, 10, etc?)

File uploads. We have http requests lasting up to 24 hours at transloadit.com, so we want to isolate those from harm (uncaught exceptions) as much as possible. Just because one upload is hitting a bug, it shouldn't crash all uploads the server is handling.

> @felixge, I'm wondering, did you build an extension to cluster that allows you to manage multiple servers each running multiple processes? I'm in need of the same functionality, but would hate to reinvent the wheel.

No, I don't even know why you'd want that. If you need to change the configuration do a graceful reload. We deploy using a custom script.

--fg

**Comment by tommedema** [comment]
@felixge, I figured you'd need a system that provides you with the following utility:
- deploy from a central source
- get log output from all server in a central place
- manage servers from a command center, eg. force restart, shutdown
- get information about each server in command center (amount of requests / min, CPU usage, current and total RAM, lifetime, amount of processes / services running)
- automatically restart masters of servers that go down to achieve high availability

I've probably forgotten something too. Do you not need such functionality?

**Comment by felixge** [comment]
> I've probably forgotten something too. Do you not need such functionality?

This is really hijacking this ticket. But anyway, we have use Munin + a few custom node, bash, and php scripts. But unfortunately they are neither open source, nor very generic.

--fg

**Comment by tommedema** [comment]
Sorry for the hijacking.

Thanks for mentioning Munin, it looks quite interesting.
