### ISSUE TITLE
Can't connect to REPL via socket

### ISSUE THREAD

**Issue by diversario** [LearnBoost/cluster#136]
I can't connect to REPL via socket no matter what. Haven't been able to do that, not once. I `.use(cluster.repl('./sock/cluster.sock'))` and when I try to telnet into it:
`telnet: could not resolve sock/cluster.sock/telnet: Name or service not known`
Same with /var/run/cluster.sock.
I can only telnet into cluster via port.
What could be the problem with this?

**Comment by tj** [comment]
from what i've seen telnet sometimes doesn't like local sockets, or you have to provide a full path, or try netcat like `nc -U path/to/cluster.sock`

**Comment by diversario** [comment]
Netcat worked with a socket, nice.

So, it is generally more reliable to listen on a port rather than socket?

**Comment by tj** [comment]
I wouldn't really say reliable but just more accessible maybe. Just make sure you bind to loopback so you dont expose the REPL haha, that could get ugly
