### ISSUE TITLE
plugins no longer receive "worker exception"

### ISSUE THREAD

**Issue by fredericosilva** [LearnBoost/cluster#142]
Hi, after this change plugins stop receiving  "worker excpetion"

https://github.com/LearnBoost/cluster/commit/ff941d5e1abc76e2e989d39a2a0db9c2e1af5fce

I discover this while playing around with cluster-mail plugin. The internal debug plugin is also not printing that exception.

**Comment by tj** [comment]
Closed by 80bcf50
