### ISSUE TITLE
v0.7.0: pid files are not updated after SIGUSR2

### ISSUE THREAD

**Issue by phuesler** [LearnBoost/cluster#143]
I've just installed the newest version and realized that our restarts do not work anymore.

We send SIGUSR2 to the pid defined in master.pid. That no longer works, because the pid files for master and the workers are NOT updated after after a SIGUSR2 to the master process.

**Comment by tj** [comment]
seems fine to me, though I did notice the restart test case was broken due to the delay with the new mkdir stuff

**Comment by phuesler** [comment]
It might have been a problem between screen and chair. I'll analyze it again and get back to you

**Comment by tj** [comment]
thanks man
