### ISSUE TITLE
cluster fail to restart when listen on unix socket

### ISSUE THREAD

**Issue by fredericosilva** [LearnBoost/cluster#151]
Hello,

There is an error on master.js#L807 

```
fs.unlink(this.port, function(err){
  if ('ENOENT' != err.code) throw err;
  startListening();
});
```

it should be 

```
fs.unlink(this.port, function(err){
  if (err && 'ENOENT' != err.code) throw err;
  startListening();
});
```

to check the case when the socket is actually removed (err is null)

keep up the work.
#### 

err: TypeError: Cannot read property 'code' of null

**Comment by tj** [comment]
fixed by b4b6350
