### ISSUE TITLE
regression in 0.7.6

### ISSUE THREAD

**Issue by poelzi** [LearnBoost/cluster#153]
this checkin causes cluster to break with kue and other strange bugs:
https://github.com/LearnBoost/cluster/commit/9cb38c8b665d2be375f423d2f6653db4c152b40d

Pressing Enter kills the master server in my case with the very uninformative traceback:

```
Error: ENOTSOCK, Socket operation on non-socket
    at Socket._readImpl (net.js:132:23)
    at Socket._onReadable (net.js:627:22)
    at IOWatcher.onReadable [as callback] (net.js:177:10)
```

Reverting the change fixes the problem.

**Comment by tj** [comment]
any steps to reproduce? I'll take a closer look in a minute
