### ISSUE TITLE
process.binding('net')

### ISSUE THREAD

**Issue by oleics** [LearnBoost/cluster#163]
Hello

process.binding('net') was removed.
https://github.com/joyent/node/wiki/API-changes-between-v0.4-and-v0.6

And maybe there are other issues with `cluster` on the official native windows build.

Thank you

**Comment by tj** [comment]
yup, there will be many issues with 0.6.x

**Comment by lonevan** [comment]
have the same problem

os: ubuntu 11.10
node : 0.6.6
cluster: 0.7.7

how to fix it?

**Comment by mjp0** [comment]
I'm having this problem too.

os: OSX 10.7
node: v0.7.10-pre
cluster: 0.7.7

Any solutions yet?

**Comment by oleics** [comment]
Use the cluster module that comes with node.js:
http://nodejs.org/dist/v0.7.9/docs/api/cluster.html

**Comment by kurteknikk** [comment]
Does this mean that this project is closed ? If yes, can somebody update the wiki page for the project to make it clear for 'potential new users' ?

**Comment by majamusan** [comment]
yeah i am having this same problem with v0.10.30
