### ISSUE TITLE
SIGKILL handling

### ISSUE THREAD

**Issue by cliffano** [LearnBoost/cluster#171]
I sent SIGKILL to cluster master, which then killed the master process, but left the worker processes running.
From lib/master.js registerSignalHandlers, I found out that cluster handles SIGINT and SIGTERM as hard shutdown, but there's no SIGKILL handling.

Shouldn't SIGKILL be considered a hard shutdown too?
Or is it by design that cluster ignores SIGKILL?

**Comment by tj** [comment]
you cant handle SIGKILL
