### ISSUE TITLE
EventEmitter

### ISSUE THREAD

**Issue by tanguylebarzic** [LearnBoost/cluster#18]
Hi, 

I tried to run the simple example in Readme.md on my computer (Ubuntu 10.10, 64bits) with node 0.4.0, but I get the following error (appears multiple times) :

  (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use       emitter.setMaxListeners() to increase limit.
Trace: 
    at [object Object].<anonymous> (events.js:101:17)
    at Socket.pipe (stream.js:67:8)
    at Master.<anonymous> (/home/tanguy/local/lib/node/.npm/cluster/0.0.3/package/lib/plugins/logger.js:136:21)
    at Master.emit (events.js:59:20)
    at Master.spawnWorker (/home/tanguy/local/lib/node/.npm/cluster/0.0.3/package/lib/master.js:310:8)
    at Master.workerKilled (/home/tanguy/local/lib/node/.npm/cluster/0.0.3/package/lib/master.js:461:12)
    at Master.invoke (/home/tanguy/local/lib/node/.npm/cluster/0.0.3/package/lib/mixins/receiver.js:51:18)
    at Master.frame (/home/tanguy/local/lib/node/.npm/cluster/0.0.3/package/lib/mixins/receiver.js:32:14)
    at Socket.<anonymous> (native)
    at Socket.emit (events.js:42:17)

Here is an extract of master.log

[Wed, 16 Feb 2011 23:32:10 GMT] INFO master started
[Wed, 16 Feb 2011 23:32:10 GMT] INFO spawned worker 0
[Wed, 16 Feb 2011 23:32:10 GMT] INFO spawned worker 1
[Wed, 16 Feb 2011 23:32:10 GMT] INFO spawned worker 2
[Wed, 16 Feb 2011 23:32:10 GMT] INFO spawned worker 3
[Wed, 16 Feb 2011 23:32:10 GMT] INFO spawned worker 4
[Wed, 16 Feb 2011 23:32:10 GMT] INFO spawned worker 5
[Wed, 16 Feb 2011 23:32:10 GMT] INFO spawned worker 6
[Wed, 16 Feb 2011 23:32:10 GMT] INFO spawned worker 7
[Wed, 16 Feb 2011 23:32:10 GMT] ERROR worker 3 died
[Wed, 16 Feb 2011 23:32:10 GMT] INFO spawned worker 3
[Wed, 16 Feb 2011 23:32:10 GMT] ERROR worker 1 died
[Wed, 16 Feb 2011 23:32:10 GMT] INFO spawned worker 1
[Wed, 16 Feb 2011 23:32:10 GMT] ERROR worker 0 died
[Wed, 16 Feb 2011 23:32:10 GMT] INFO spawned worker 0
[Wed, 16 Feb 2011 23:32:10 GMT] ERROR worker 5 died
[Wed, 16 Feb 2011 23:32:10 GMT] INFO spawned worker 5
[Wed, 16 Feb 2011 23:32:10 GMT] ERROR worker 2 died
[Wed, 16 Feb 2011 23:32:10 GMT] INFO spawned worker 2
[Wed, 16 Feb 2011 23:32:10 GMT] ERROR worker 6 died
[Wed, 16 Feb 2011 23:32:10 GMT] INFO spawned worker 6
[Wed, 16 Feb 2011 23:32:10 GMT] ERROR worker 4 died
[Wed, 16 Feb 2011 23:32:10 GMT] INFO spawned worker 4
[Wed, 16 Feb 2011 23:32:10 GMT] ERROR worker 7 died
[Wed, 16 Feb 2011 23:32:10 GMT] INFO spawned worker 7
[Wed, 16 Feb 2011 23:38:26 GMT] ERROR worker 7 died
[Wed, 16 Feb 2011 23:38:26 GMT] INFO spawned worker 7
[Wed, 16 Feb 2011 23:38:26 GMT] ERROR worker 6 died

Not sure if this is cluster-specific though...

Thanks in advance!

**Comment by tj** [comment]
yeah its a stupid node thing, looking into a fix

**Comment by tanguylebarzic** [comment]
Thanks for your quick answer!

**Comment by tj** [comment]
Fixed event leak. Closed by 37d07152da4bff2be77b24b4e0d640e47d0a957c

give each worker its own writable stream
