### ISSUE TITLE
Future of LearnBoost/cluster?

### ISSUE THREAD

**Issue by enyo** [LearnBoost/cluster#184]
Is there any future for this module? Should I just use node's cluster? Are you working on a new module?

Thanks..

**Comment by enyo** [comment]
Oh and @visionmedia : what do you use now? Just node's cluster? Or https://github.com/ql-io/cluster2 ? Or another library?

**Comment by rauchg** [comment]
Node's cluster.

**Comment by enyo** [comment]
Thanks
