### ISSUE TITLE
does not output console.log()

### ISSUE THREAD

**Issue by rcrd88** [LearnBoost/cluster#19]
I am using latest Express with cluster, my node version is v0.4
        var cluster = require('cluster');
        var express = require('express');
        var app = module.exports = express.createServer();

```
    app.get('/', function(req, res){

      console.log('New Request'); // this does not output

      res.render('index', { title: 'Express' });
    });

    cluster(app)
        .use(cluster.logger('logs'))
        .use(cluster.stats())
        .use(cluster.pidfiles('pids'))
        .use(cluster.cli())
        .use(cluster.repl(8888))
        .use(cluster.reload(['app.js']))
        .use(cluster.debug())
        .listen(3000);
```

It doestn't output the message using console.log() in the console or master.log or workers.access.log.
I am not sure it is a bug or by design?
Thanks

**Comment by tj** [comment]
in the case above it should write to the worker access log, my examples that have logger() do this, and they do work, the test passes as well

**Comment by tj** [comment]
master itself will still output to stdout/stderr

**Comment by rcrd88** [comment]
sorry, it actually do write to workers.access.log.

and it would be useful output message in the console for easy debuging. :)

Thanks very much!

**Comment by tj** [comment]
if you need that then just comment out the logger() line, or add it conditionally when in development

**Comment by rcrd88** [comment]
Thanks very much, it worked!
