### ISSUE TITLE
Support bind to domain name

### ISSUE THREAD

**Issue by lsm** [LearnBoost/cluster#35]
```
cluster(server)
  .listen(80, 'example.com');
```

**Comment by EyePulp** [comment]
I second this - I get an error when trying to bind to a hostname:  
Error: Unknown socket type.
at Master.createSocket (/cluster/lib/master.js:323:20)

**Comment by tj** [comment]
Added listen() host dns resolution. Closed by a452dbdde26aecdf90992aeee7fc51df368fb29b
