### ISSUE TITLE
spawn(-x)

### ISSUE THREAD

**Issue by dvv** [LearnBoost/cluster#46]
Feasible to make spawn honor negative numbers to decrease the number of workers?

--Vladimir++

**Comment by tj** [comment]
yeah certainly could do

**Comment by dvv** [comment]
I drafted in the pull request

**Comment by TheDeveloper** [comment]
Currently calling spawn(-1) appears to spawn an infinite number of workers. Is there a way to currently decrease the number of workers in realtime, or can you only add them?

**Comment by tj** [comment]
Added spawn(-n) support. Closed by 3aa1533cef115961c50d963f4b1d83df18589aa8
