### ISSUE TITLE
Not working under Cygwin

### ISSUE THREAD

**Issue by carlosedp** [LearnBoost/cluster#49]
My Express application starts with no errors and spawns the workers but the site is not accessible when started under Cygwin.

On MacOS it works perfectly.

**Comment by tj** [comment]
does cygwin support fd passing?

**Comment by carlosedp** [comment]
I don't think so. I found a TODO listing a workaround on:
http://wiki.osdev.org/Cygwin_Issues#Passing_file_descriptors

Thanks for your attention.
