### ISSUE TITLE
issue : created 100's of processes

### ISSUE THREAD

**Issue by weepy** [LearnBoost/cluster#53]
heya 

I've just been trying this out. I had a major issue - where upon a restart request it got into a pickle. 

I think the problem was due to the restarting code. Upon starting my server does a little bit of compilation of some javascript. --  would it be a good idea to have a little grace period ? 

Here's the gist.

https://gist.github.com/863877

**Comment by tj** [comment]
let me guess, coffeescript :p

it seems like reload() is maybe detecting the change in .js and causing the restart

**Comment by weepy** [comment]
not CS - I gave up that addiction long ago ^_^

.... it was due to an asset packager tho ... so my fault really. BUT if there was a grace period of a few hundred ms, there wouldn't be nearly 1000 processes ^_^

**Comment by tj** [comment]
oh ! haha nvm then.

yeah I know what you mean, there is certainly a BIG issue when an issue occurs. I would like to add some locking so that recursive restarts do not happen, or at least much slower

**Comment by tj** [comment]
this will help as well https://github.com/LearnBoost/cluster/commit/87f3b6d76fc5af1b4fb2d99feb62fe15e3bd025b

later we should detect and just bail
