### ISSUE TITLE
tracking down problemo

### ISSUE THREAD

**Issue by weepy** [LearnBoost/cluster#55]
Hiya

I don't know which lib is at fault here. 

my app works fine normally running with node, but when i use cluster, I get : 

Error: EINVAL, Invalid argument
    at IOWatcher.callback (net.js:878:24)

but that's it --> and line 878 of node's net is

<pre>
while (self.fd) { 
</pre>

there are no other net.js files on my system.

running on :  node 4.2, cluster 4,1, express2.0.0beta

**Comment by dvv** [comment]
see "Spiky EINVAL" issue

**Comment by tj** [comment]
closing the duplicate, will try and debug this soon
