### ISSUE TITLE
Error: ESRCH, No such process

### ISSUE THREAD

**Issue by weepy** [LearnBoost/cluster#56]
After a work starts and then dies, running stop gives an error

<pre>
node boot stop
</pre>

nb boot is a js file with the cluster commands in

<pre>
node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: ESRCH, No such process
    at EventEmitter.kill (node.js:203:19)
    at Object.callback (/u/apps/mewcal2/node_modules/.npm/cluster/0.4.1/package/lib/plugins/cli.js:177:11)
    at /u/apps/mewcal2/node_modules/.npm/cluster/0.4.1/package/lib/plugins/cli.js:76:19
    at Master.use (/u/apps/mewcal2/node_modules/.npm/cluster/0.4.1/package/lib/master.js:335:25)
    at Object.<anonymous> (/u/apps/mewcal2/boot:15:4)
    at Module._compile (module.js:383:26)
    at Object..js (module.js:389:10)
    at Module.load (module.js:315:31)
    at Function._load (module.js:276:12)
    at Array.<anonymous> (module.js:402:10)
</pre>

**Comment by tj** [comment]
hmm and you are using `pidfiles()` before? that line is

```
  process.kill(master.pidof('master'), 'SIGTERM');
```

try console.log()ing the pidof() thing there. seems like maybe the pidfile is getting trashed or not working all together

**Comment by weepy** [comment]
here you go : 

<pre>

root@yumoov:/u/apps/mewcal2# node boot start
  info - master started
  info - worker 0 spawned
  info - worker 0 connected
  info - listening for connections
  error - worker 0 uncaught exception EINVAL, Invalid argument
  warning - worker 0 died
  info - worker 0 spawned
  info - worker 0 connected
  info - shutting down
  warning - kill(SIGKILL)
  info - shutdown complete
  debug - exit
root@yumoov:/u/apps/mewcal2# node boot stop
30415

node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: ESRCH, No such process
    at EventEmitter.kill (node.js:203:19)
    at Object.callback (/u/apps/mewcal2/node_modules/.npm/cluster/0.4.1/package/lib/plugins/cli.js:178:11)
    at /u/apps/mewcal2/node_modules/.npm/cluster/0.4.1/package/lib/plugins/cli.js:76:19
    at Master.use (/u/apps/mewcal2/node_modules/.npm/cluster/0.4.1/package/lib/master.js:335:25)
    at Object.<anonymous> (/u/apps/mewcal2/boot:15:4)
    at Module._compile (module.js:383:26)
    at Object..js (module.js:389:10)
    at Module.load (module.js:315:31)
    at Function._load (module.js:276:12)
    at Array.<anonymous> (module.js:402:10)

</pre>

**Comment by tj** [comment]
well looks like it already died, SIGINT / SIGTERM send SIGKILL to the children so looks like you got one of those two before calling `node boot stop`

**Comment by weepy** [comment]
yes you're right. it even says it in the log "error - worker 0 uncaught exception EINVAL, Invalid argument"

I suppose it would be nice to handle this case more friendly ?

**Comment by tj** [comment]
but it shouldnt show "shutting down\n  warning - kill(SIGKILL)" unless you are signaling it, that part doesnt look normal, the worker re-spawning on death is fine but the master shouldnt just shut down like that

**Comment by weepy** [comment]
node boot looks like :

#!/usr/local/bin/node

var config = require("./config"),
    cluster = require('cluster')

var server =

cluster("./app")
  .set("workers", 1)
  .set('socket path', 'sys')
  .use(cluster.logger('sys/logs'))
  .use(cluster.stats())
  .use(cluster.pidfiles('sys/pids'))
  .use(cluster.cli())
  .use(cluster.debug())
  .use(cluster.repl(config.repl_port || 8888), '127.0.0.1')
  .listen(config.port, config.host)

**Comment by tj** [comment]
looks fine, try using just `debug()`, see if that is fine

**Comment by weepy** [comment]
it's already there ?

**Comment by tj** [comment]
with _just_ debug() :p process of elimination

**Comment by weepy** [comment]
ok with _just_ debug: 

<pre>
root@yumoov:/u/apps/mewcal2# node boot 
  info - master started
  info - worker 0 spawned
  info - worker 1 spawned
  info - worker 2 spawned
  info - worker 3 spawned
  info - worker 0 connected
Error: EINVAL, Invalid argument
    at IOWatcher.callback (net.js:878:24)
  error - worker 0 uncaught exception EINVAL, Invalid argument
  warning - worker 0 died
  info - worker 0 spawned
  info - worker 3 connected
Error: EINVAL, Invalid argument
    at IOWatcher.callback (net.js:878:24)
  error - worker 3 uncaught exception EINVAL, Invalid argument
  warning - worker 3 died
  info - worker 3 spawned
Error: EINVAL, Invalid argument
    at IOWatcher.callback (net.js:878:24)
  info - worker 1 connected
  error - worker 1 uncaught exception EINVAL, Invalid argument
  warning - worker 1 died
  info - worker 1 spawned
  info - worker 2 connected
  info - listening for connections
  info - worker 3 connected
  info - worker 1 connected
  info - worker 0 connected
  info - shutting down
  warning - kill(SIGKILL) <---- that's me doing Ctrl+C
  info - shutdown complete
  debug - exit
</pre>

**Comment by tj** [comment]
I think this is the same issue as the other EINVAL, closing
