### ISSUE TITLE
early exception in app can crash cluster

### ISSUE THREAD

**Issue by bkw** [LearnBoost/cluster#57]
When an app suffers from an error event before the worker has received its worker.id from the master connection, the calling of workerException() cannot supply a worker.id. Subsequently the logging of the exception throws because the the error event actually ends up in `worker` and `err` is empty (see below).

Sorry, no quick fix. Using `this.id || 0` when unshifting the arguments works since we always should have some worker with id 0, but logging exceptions is the wrong place to cheat ;-)
I'm sure you can come up with a better solution.

This testcase may seem fabricated but it actually bit me, when an express app failed to connect its database handle during app.configure().

app.js:

```
var http = require('http');
var app = module.exports = http.createServer(function(){});
// provoke exception:
http.request({host:'localhost', 'port':1});
```

server.js:

```
var cluster = require('cluster');
cluster('./app.js')
  .use(cluster.logger('.'))
  .listen(3000);
```

% node server.js

```
/usr/local/lib/node/.npm/cluster/0.4.1/package/lib/plugins/logger.js:81
  log.error('worker ' + worker.id + ' uncaught exception ' + err.message);
                                                                ^
TypeError: Cannot read property 'message' of undefined
  at Master.<anonymous> (/usr/local/lib/node/.npm/cluster/0.4.1/package/lib/plugins/logger.js:81:69)
at Master.emit (events.js:45:17)
at Master.workerException (/usr/local/lib/node/.npm/cluster/0.4.1/package/lib/master.js:784:8)
at Master.invoke (/usr/local/lib/node/.npm/cluster/0.4.1/package/lib/mixins/receiver.js:51:18)
at Master.frame (/usr/local/lib/node/.npm/cluster/0.4.1/package/lib/mixins/receiver.js:32:14)
at Socket.<anonymous> (native)
at Socket.emit (events.js:42:17)
at Socket._onReadable (net.js:644:31)
at IOWatcher.onReadable [as callback] (net.js:156:10)
```

**Comment by tj** [comment]
hmm, yeah I may have to emit a different even here to deal with these premature failures, and remove the worker all together because if we keep hitting the maintain worker count logic it will just keep spawning them indefinitely which is not ideal if boot logic is faulty
