### ISSUE TITLE
reload plugin

### ISSUE THREAD

**Issue by jorisroling** [LearnBoost/cluster#58]
Hi,

It seems that making use of the reload plugin makes that a subsequent **node server.js --status** call needs to be stopped by CTRL-C.

Does anyone else have this too?

Cheers,
Joris

**Comment by dvv** [comment]
I do. debian 6.0, 32-bit

**Comment by jorisroling** [comment]
Mac SnowLeopard here...

**Comment by jorisroling** [comment]
Fixed it:
https://github.com/LearnBoost/cluster/pull/59

**Comment by tj** [comment]
ah, yeah since I was using `preventDefault` instead of exit(). I can switch it back

**Comment by tj** [comment]
closed by ada9aca84a44f79f137ae1ceb5628ab63e0f8575
