### ISSUE TITLE
Is it possible to cluster non-http workers?

### ISSUE THREAD

**Issue by ybogdanov** [LearnBoost/cluster#72]
Hi,

I mean, if I need to cluster some node processes which are doing other stuff than serving http? For example, background workers which pulls a queue from redis and performs some jobs.

The idea is to make an abstract worker which implements some interface and extend http worker from it. This makes possible to cluster other kinds of workers, not just those which serves http. 

Thank you!

**Comment by tj** [comment]
any node server should work, TCP, UDP, HTTP etc, however one of those is (currently) required

**Comment by ybogdanov** [comment]
But what if my process doesn't have any server? It just connects to pub/sub and do some stuff?

**Comment by tj** [comment]
currently that wont work, but I would like to add support for that, most the plugins are pretty http specific, but no reason we cant support this

**Comment by ybogdanov** [comment]
I'm not promise, but maybe I'll make a fork for that.
If it's not hard for you, please give me a direction.

**Comment by tj** [comment]
basically anything working with `Master#server` just needs to be conditional

**Comment by ybogdanov** [comment]
Please, take a look at 0ctave/cluster@be89bef013f417e91a3e37da4a6137abfea06779 draft. Still don't understand how teach cluster not to listen port, just to run.
Restarting works well.

So, the interface of "server" object being clustered is pretty simple: start() and stop() methods.
