### ISSUE TITLE
new v8 isolates api - may be a good update for node-cluster

### ISSUE THREAD

**Issue by ybogdanov** [LearnBoost/cluster#73]
Hi,

[v8 changelog updated recently](http://code.google.com/p/v8/source/browse/trunk/ChangeLog):

```
2011-03-23: Version 3.2.4
Added isolates which allows several V8 instances in the same process.
This is controlled through the new Isolate class in the API.
```

So, we don't even need to spawn child processes to run in multi-cores anymore. Your ideas gentlemen?

**Comment by egorFiNE** [comment]
<code>several V8 instances in the same process</code>

A single process cannot scale to multiple CPUs unless the process is threaded.

**Comment by ybogdanov** [comment]
Shit.

**Comment by tj** [comment]
what he said

**Comment by kainosnoema** [comment]
With the work @ry's doing on "domains" to bring V8 isolates into Node (its now on the [roadmap for v0.8](http://groups.google.com/group/nodejs/browse_thread/thread/79504e62223f3bf0)), this might not be so far fetched after all. From what I've been able to tell from the [initial commits towards this](https://github.com/joyent/node/commits/domains), the domains module will create a wrapper around all I/O related to specific block of code (ie. a network request), and automatically clean up any open handles (fs, db, etc) if an error is thrown. This is the first baby step towards being able to use threads reliably, without fear of any one thread bringing down the process.

This is all very exciting, and definitely seems to imply that tools like cluster could be built to run in multiple threads within a single Node process in the future, but the benefits are less clear. For one, V8 isolates [do not share any memory](http://groups.google.com/group/nodejs/msg/7d23fef512fe9088) (that's the point, they "isolate" your code). This guarantees that your code is safe (even if it's not threadsafe), but also means that many of the benefits of threads like faster spawning and lower memory usage will be much less pronounced. We'll have to wait and see how this actually plays out.
