### ISSUE TITLE
connect sessions and cluster

### ISSUE THREAD

**Issue by pnitsch** [LearnBoost/cluster#77]
Might be more related to connect than cluster, but it's something to be aware of. I've been playing with a web app that uses connect sessions heavily. With two workers spawned the session id can occasionally change, most likely due to the request being handled by a different worker than the previous request. 

Not sure if there's a workaround. I might try to write my own store and pass id's along with the request. Dunno.

**Comment by tj** [comment]
what session store are you using? if it's the memory store, then use something persistant like connect-redis etc

**Comment by pnitsch** [comment]
Worked like a charm. Thanks for pointing out that lib.

**Comment by tj** [comment]
relying on memory state is usually bad :p memory store is only good for testing really

**Comment by pnitsch** [comment]
I was unaware. Glad I posted the issue. :)
