### ISSUE TITLE
async startup

### ISSUE THREAD

**Issue by donpark** [LearnBoost/cluster#78]
Any plan to support apps that starts up asynchronously? The fact that node's `require` neither blocks nor support callback is getting in the way of making my app cluster-ready.

**Comment by tj** [comment]
node's require does block

**Comment by donpark** [comment]
I meant blocking cannot be controlled. It just blocks while the module load and evaluates. If I need to defer returning until, say connection completes, I don't see a way to do that.

**Comment by tj** [comment]
you can do whatever you want as far as deferring the listen() call, but I kinda see what you mean, it would be kinda nice to have this functionality for plugins as well so they can defer until they are ready, but usually irrelevant
