### ISSUE TITLE
Crash on start without 'pids' or 'logs' folders

### ISSUE THREAD

**Issue by marcello3d** [LearnBoost/cluster#79]
When using `cluster.use(cluster.pidfiles('pids'))` without a pids folder, cluster crashes on start:

```
<...>/node_modules/cluster/lib/plugins/pidfiles.js:42
    function fn(err){ if (err) throw err; }
                               ^
Error: ENOENT, No such file or directory '<...>/pids/worker.0.pid'
```

The same occurs with the logs plugin. If you're requiring the user to make that folder themselves, it'd be nice to have a more explicit error message. Or just make the folder.

**Comment by tj** [comment]
yeah we could make the dirs, just sucks that node does not have a mkdir -p equiv, exec() feels dirty for this stuff but it would beat some 50 line thing in node

**Comment by tj** [comment]
we have mkdir-p stuff now
