### ISSUE TITLE
Using a Proxy with cluster

### ISSUE THREAD

**Issue by seflless** [LearnBoost/cluster#87]
What's the recommend way of using a proxy so that I can redirect specific URLs to an apache server, motivation being to have my blog at http://emotely.com/blog/* and the rest going to my node.js based http://emotely.com/.

I'm currently using node-http-proxy. But it's designed to spawn another server itself so I can't figure out how to get it work with the exporting your server style architecture. node-http-proxy seems unstable so I wanted to use cluster on top of it to resuscitate workers when they go down.

Thanks for the helps,
Francois

**Comment by seflless** [comment]
Maybe some one has another recommendation. Like using nginx in front of cluster to deal with the URL based forward and then leaving cluster to distributing the request as normal. I'd heard that there were issues getting nginx to work well with node.

**Comment by s3u** [comment]
Don't use node-http-proxy. I can't trust it as a general purpose production worthy proxy server yet. We also don't know about all security holes in Node for it to serve traffic on port 80. Try Apache Traffic Server or Nginx as a proxy. The former does HTTP/1.1 between the proxy and node cluster and hence can deal better with traffic. If it is for a personal blog, nginx should be fine.

**Comment by seflless** [comment]
Thanks. I ended up using nginx, which worked out fine. Well except the inability now to WebSockets easily. I set up another server dedicated to WebSocket usage.

**Comment by tj** [comment]
good to close?

**Comment by seflless** [comment]
Yes. Closed it.
