### ISSUE TITLE
Exception on finishing of  examples / standalone.js

### ISSUE THREAD

**Issue by Arech** [LearnBoost/cluster#89]
Hi!

I've just tried https://github.com/LearnBoost/cluster/blob/master/examples/standalone.js and got exception instead of gracefull shutdown. Here is the end of the console log:
# 

  info - shutting down
  warning - kill(SIGQUIT)
  warning - worker 0 died
  warning - worker 1 died
  warning - worker 2 died
  warning - worker 3 died

... /node_modules/cluster/lib/master.js:741
    binding.close(self.fd);
            ^
TypeError: Bad file descriptor argument
    at Server.<anonymous> ( ... /node_modules/cluster/lib/master.js:741:13)
    at Server.emit (events.js:61:17)
    at net.js:1147:12
# 

Looks like the shutdown procedure is broken here.
Feel free to ask more info if needed.

**Comment by tj** [comment]
thanks I'll take a look at this right away
