### ISSUE TITLE
Why doesn't node.js already include this magic cluster stuff?

### ISSUE THREAD

**Issue by binarykitchen** [LearnBoost/cluster#96]
... I'm just asking that because I think node.js should have that multi-core support by default.

**Comment by binarykitchen** [comment]
Then this benchmark would have shown better results for node.js ;)
http://www.ostinelli.net/a-comparison-between-misultin-mochiweb-cowboy-nodejs-and-tornadoweb/

**Comment by tommedema** [comment]
Why is that? Benchmarks can use libraries -- node should be the core, in other words as minimal as possible.

**Comment by binarykitchen** [comment]
I don't know. "Minimal" is a question of definition. IMO it's worth to consider whether a minimal node.js setup should support multi-cores or not these days.

**Comment by tommedema** [comment]
I wouldn't say so, since using cluster is not as straightforward as a single process app. Thus, a minimal node.js setup should probably not be using it.

**Comment by binarykitchen** [comment]
I understand, you are right in that aspect. But when it comes to benchmarks, being competitive, then that's another perspective.

**Comment by tj** [comment]
I think it's too opinionated for node, personally I dont really see it belonging in core, we've already seen drastically different implementations with spark/fugue/cluster etc

**Comment by binarykitchen** [comment]
Ok. I wasn't reading carefully enough, this benchmark test was using one core only.
